### ISSUE TITLE
Add non-static DFA.intersect(dfa) and NFA.intersect(nfa) methods

### ISSUE THREAD

**Issue by not-my-profile** [RunDevelopment/refa#21]
I think non-static methods i.e. `dfa1.intersect(dfa2)` would make the intersection API more discoverable (I nearly opened an issue because I initially didn't find `DFA.fromIntersection()`).

**Comment by RunDevelopment** [comment]
`fromIntersection` is a static method on both `NFA` and `DFA` because the return type of `fa1.intersect(fa2)` isn't well-defined. If both FAs are either DFAs or NFAs, then the result can be a DFA or NFA respectively. 

But what should `nfa.intersect(dfa)` and `dfa.intersect(nfa)` return? 

Intersection is a commutative operation, so ideally the return type of both should be the same. I also plan to add epsilon-NFAs in the future, so the solution has to scale with potentially many FA kinds. 
And the solution has to be simple of course! :)

Well, those are the reasons I went with static methods but I do agree that the API is a little hidden. This is more of a documentation issue instead of an API issue, IMO.

**Comment by not-my-profile** [comment]
Fair enough. Thanks for the quick response! Yeah I agree that the documentation can be improved ... maybe set up something like [typedoc](https://github.com/TypeStrong/typedoc)?

**Comment by RunDevelopment** [comment]
I opened #22 for Typedoc. 

However, it will likely take some time until I can actually use Typedoc because it has a bug that causes it to not generate documentation for the `JS` namespace.
